import pymel.core as py


def connect_locators():
    py.connectControl('locator_scale', "rt_up_eye_inner_L.scaleX",
                      "lf_up_eye_inner_L.scaleX",
                      "rt_up_eye_mid_L.scaleX",
                      "lf_up_eye_mid_L.scaleX",
                      "rt_up_eye_outer_L.scaleX",
                      "lf_up_eye_outer_L.scaleX",
                      "rt_low_eye_outer_L.scaleX",
                      "lf_low_eye_outer_L.scaleX",
                      "rt_low_eye_mid_L.scaleX",
                      "lf_low_eye_mid_L.scaleX",
                      "rt_low_eye_inner_L.scaleX",
                      "lf_low_eye_inner_L.scaleX",
                      "rt_upper_cheek_L.scaleX",
                      "lf_upper_cheek_L.scaleX",
                      "rt_low_cheek_L.scaleX",
                      "lf_low_cheek_L.scaleX",
                      "rt_nose_L.scaleX",
                      "lf_nose_L.scaleX",
                      "rt_outer_cheek_L.scaleX",
                      "lf_outer_cheek_L.scaleX",
                      "rt_mouth_up_outermid_L.scaleX",
                      "lf_mouth_up_outermid_L.scaleX",
                      "rt_mouth_outer_L.scaleX",
                      "lf_mouth_outer_L.scaleX",
                      "cn_mouth_center_up_L.scaleX",
                      "rt_mouth_up_innermid_L.scaleX",
                      "lf_mouth_up_innermid_L.scaleX",
                      "rt_mouth_low_innermid_L.scaleX",
                      "lf_mouth_low_innermid_L.scaleX",
                      "rt_mouth_low_outermid_L.scaleX",
                      "lf_mouth_low_outermid_L.scaleX",
                      "cn_mouth_center_low_L.scaleX",
                      "cn_head_L.scaleX",
                      "cn_head_low_jaw_L.scaleX")


def connect_offset():
    py.connectControl('offset_scale', "rt_up_eye_inner_offset.scaleX",
                      "lf_up_eye_inner_offset.scaleX",
                      "rt_up_eye_mid_offset.scaleX",
                      "lf_up_eye_mid_offset.scaleX",
                      "rt_up_eye_outer_offset.scaleX",
                      "lf_up_eye_outer_offset.scaleX",
                      "rt_low_eye_outer_offset.scaleX",
                      "lf_low_eye_outer_offset.scaleX",
                      "rt_low_eye_mid_offset.scaleX",
                      "lf_low_eye_mid_offset.scaleX",
                      "rt_low_eye_inner_offset.scaleX",
                      "lf_low_eye_inner_offset.scaleX",
                      "rt_upper_cheek_offset.scaleX",
                      "lf_upper_cheek_offset.scaleX",
                      "rt_low_cheek_offset.scaleX",
                      "lf_low_cheek_offset.scaleX",
                      "rt_nose_offset.scaleX",
                      "lf_nose_offset.scaleX",
                      "rt_outer_cheek_offset.scaleX",
                      "lf_outer_cheek_offset.scaleX",
                      "rt_mouth_up_outermid_offset.scaleX",
                      "lf_mouth_up_outermid_offset.scaleX",
                      "rt_mouth_outer_offset.scaleX",
                      "lf_mouth_outer_offset.scaleX",
                      "cn_mouth_center_up_offset.scaleX",
                      "rt_mouth_up_innermid_offset.scaleX",
                      "lf_mouth_up_innermid_offset.scaleX",
                      "rt_mouth_low_innermid_offset.scaleX",
                      "lf_mouth_low_innermid_offset.scaleX",
                      "rt_mouth_low_outermid_offset.scaleX",
                      "lf_mouth_low_outermid_offset.scaleX",
                      "cn_mouth_center_low_offset.scaleX")